VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDataMap"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Description = "Abstracts storage interfaces for DataMapModel."
'@Folder "Storage.Map.Abstract"
'@ModuleDescription "Abstracts storage interfaces for DataMapModel."
'@Interface
'@Exposed
Option Explicit


Public Sub GetData(ByVal ConnectionString As String, ByVal FieldNames As Variant)
End Sub
