VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISheetAProxy"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "WorkbookProxyExampleDialog.Abstract"
Option Explicit

Public Property Get Code() As String
End Property

Public Property Let Code(ByVal Value As String)
End Property

Public Property Get Value() As String
End Property

Public Property Let Value(ByVal Value As String)
End Property

