VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISheet1Proxy"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get Field1() As String
End Property

Public Property Let Field1(ByVal value As String)
End Property

Public Property Get Field2() As String
End Property

Public Property Let Field2(ByVal value As String)
End Property

Public Sub Clear()
End Sub

