VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISheetAProxy"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "Forms.Abstract"
Option Explicit

Public Property Get FieldA() As String
End Property

Public Property Let FieldA(ByVal value As String)
End Property

Public Property Get FieldB() As String
End Property

Public Property Let FieldB(ByVal value As String)
End Property

Public Sub Clear()
End Sub

