@echo off
rem md "%rP"
rem xcopy /Y/B "%F" "%rD"

md "ContactEditor\Forms\Abstract"
md "ContactEditor\Forms\Contact Browser"
md "ContactEditor\Storage\Composite Manager"
md "ContactEditor\Storage\Record\Backend"
md "ContactEditor\Storage\Record\Factory"
md "ContactEditor\Storage\Record\Manager"
md "ContactEditor\Storage\Record\Model"
md "ContactEditor\Storage\Table\Backend"
md "ContactEditor\Storage\Table\Factory"
md "ContactEditor\Storage\Table\Manager"
md "ContactEditor\Storage\Table\Model"
md "Common\Excel Objects"
md "Common\Guard\Tests"
md "Common\Shared\WinAPI"

xcopy /Y/B "CommonRoutines.bas" "Common\Shared"
xcopy /Y/B "CommonStructuresForErrors.bas" "Common\Guard"
xcopy /Y/B "ContactBrowserRunner.bas" "ContactEditor\Forms\Contact Browser"
xcopy /Y/B "DataCompositeManagerTests.bas" "ContactEditor\Storage\Composite Manager"
xcopy /Y/B "DataRecordFactoryTests.bas" "ContactEditor\Storage\Record\Factory"
xcopy /Y/B "DataRecordManagerTests.bas" "ContactEditor\Storage\Record\Manager"
xcopy /Y/B "DataRecordWSheetTests.bas" "ContactEditor\Storage\Record\Backend"
xcopy /Y/B "DataTableFactoryTests.bas" "ContactEditor\Storage\Table\Factory"
xcopy /Y/B "DataTableManagerTests.bas" "ContactEditor\Storage\Table\Manager"
xcopy /Y/B "DataTableWSheetTests.bas" "ContactEditor\Storage\Table\Backend"
xcopy /Y/B "GuardTests.bas" "Common\Guard\Tests"
xcopy /Y/B "SharedStructuresForTests.bas" "Common\Guard\Tests"
xcopy /Y/B "ShellRoutines.bas" "Common\Shared"
xcopy /Y/B "StorageDescription.bas" "ContactEditor\Storage"
xcopy /Y/B "TestRunner.bas" "ContactEditor\Storage"
xcopy /Y/B "WinAPI.bas" "Common\Shared\WinAPI"
xcopy /Y/B "ContactBrowserModel.cls" "ContactEditor\Forms\Contact Browser"
xcopy /Y/B "ContactBrowserPresenter.cls" "ContactEditor\Forms\Contact Browser"
xcopy /Y/B "DataCompositeManager.cls" "ContactEditor\Storage\Composite Manager"
xcopy /Y/B "DataRecordFactory.cls" "ContactEditor\Storage\Record\Factory"
xcopy /Y/B "DataRecordManager.cls" "ContactEditor\Storage\Record\Manager"
xcopy /Y/B "DataRecordModel.cls" "ContactEditor\Storage\Record\Model"
xcopy /Y/B "DataRecordWSheet.cls" "ContactEditor\Storage\Record\Backend"
xcopy /Y/B "DataTableFactory.cls" "ContactEditor\Storage\Table\Factory"
xcopy /Y/B "DataTableManager.cls" "ContactEditor\Storage\Table\Manager"
xcopy /Y/B "DataTableModel.cls" "ContactEditor\Storage\Table\Model"
xcopy /Y/B "DataTableWSheet.cls" "ContactEditor\Storage\Table\Backend"
xcopy /Y/B "Guard.cls" "Common\Guard"
xcopy /Y/B "IDataRecordFactory.cls" "ContactEditor\Storage\Record\Factory"
xcopy /Y/B "IDataRecordManager.cls" "ContactEditor\Storage\Record\Manager"
xcopy /Y/B "IDataRecordStorage.cls" "ContactEditor\Storage\Record\Backend"
xcopy /Y/B "IDataTableFactory.cls" "ContactEditor\Storage\Table\Factory"
xcopy /Y/B "IDataTableManager.cls" "ContactEditor\Storage\Table\Manager"
xcopy /Y/B "IDataTableStorage.cls" "ContactEditor\Storage\Table\Backend"
xcopy /Y/B "IDialogView.cls" "ContactEditor\Forms\Abstract"
xcopy /Y/B "Config.doccls" "Common\Excel Objects"
xcopy /Y/B "ContactBrowser.doccls" "Common\Excel Objects"
xcopy /Y/B "Contacts.doccls" "Common\Excel Objects"
xcopy /Y/B "Playground.doccls" "Common\Excel Objects"
xcopy /Y/B "TestSheet.doccls" "Common\Excel Objects"
xcopy /Y/B "ThisWorkbook.doccls" "Common\Excel Objects"
xcopy /Y/B "ContactBrowserForm.frm" "ContactEditor\Forms\Contact Browser"
xcopy /Y/B "ContactBrowserForm.frx" "ContactEditor\Forms\Contact Browser"
